apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ugc-demo.fullname" . }}-sophora-properties
  labels:
    {{- include "ugc-demo.labels" . | nindent 4 }}
data:
  sophora.properties: |-

    {{ toString (required "A valid sophora.properties configuration needs to be provided." .Values.ugc.demo.sophoraproperties) | nindent 4  }}
