apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowledge-base.fullname" . }}
  labels:
    {{- include "knowledge-base.labels" . | nindent 4 }}
data:
  application.yml: |-
    sophora:
      client:
        server-connection:
          urls:
          {{- range .Values.api.sophora.connection.urls }}
            - {{ . | quote }}
          {{- end }}
        tool-info:
          name: "knowledge-base-backend"
    server:
      port: 8181

    spring:
      groovy:
        template:
          check-template-location: false