apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifactory-search.fullname" . }}
  labels:
    {{- include "artifactory-search.labels" . | nindent 4 }}
data:
  application.yml: |- {{ toYaml (required "A valid application.yaml config is required (nested in the value .Values.artifactorySearch.config)!" .Values.artifactorySearch.config) | nindent 4 }}