apiVersion: v2
name: group-challenge
description: Group challenge helm chart
type: application
version: 1.2.0
appVersion: "0.10.0"
dependencies:
  - name: postgresql
    version: 11.9.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled