frontend:
  image:
    repository: docker.subshell.com/labday/dependency-db-frontend
    pullPolicy: Always
    tag: "1.0.0"
  container:
    resources:
      requests:
        cpu: 999m
        memory: 123Mi
      limits:
        cpu: 888m
        memory: 4321Mi

api:
  image:
    repository: docker.subshell.com/labday/dependency-db-api
    pullPolicy: Always
    tag: "1.0.0"
  container:
    resources:
      requests:
        cpu: 222m
        memory: 42Mi
      limits:
        cpu: 333m
        memory: 1337Mi
  config:
    basepoms:
      coordinates:
        - "com.subshell.sophora:basepom"
        - "com.subshell.sophora:kotlin-basepom"

imagePullSecrets: []
nameOverride: "test-name-override"
fullnameOverride: "full-test-name-override"

podAnnotations:
  my/test/annotation: "foo"
  my/other/annotation: "bar"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - frontend.dependency-db.test
    - frontend2.dependency-db.test
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}